title = "Ito Collection"
baseURL = "https://itoschum.me"
languageCode = "en-us"
theme = "ananke"
themesDir = "./themes"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Stay hungry. Stay foolish."
  facebook = "https://www.facebook.com/ItoShen"
  twitter = "https://twitter.com/Ito_Shen"
  instagram = ""
  youtube = "https://www.youtube.com/channel/UCFxxWKktr2IjvTKxy33luZQ"
  github = "https://github.com/ItoSchum"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/yitao-shen-9869b3132/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  body_classes = "avenir bg-near-white"
  featured_image = "/images/background/miku_2B_remix.jpg"
  recent_posts_number = 3
  disqusShortname = "itoschum-me"
